# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdddf37f55c68603b6473b05a1c237ec7559643c3c45a0d006dc5c064ea98e0b485edf972862efedfe934546478139b801c68c20b48347e80f8757dce6ebd64e

test:
  secret_key_base: 7d1da45795fe3937edde61ddf7808a8d776ffac2a4329c5306b64b045c85ac1d89cb38875563b0ab7899568a96fb167bac4b0c5dff94d5693928dce4cf285bb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
